# Generated by Django 4.2.7 on 2023-12-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon_title', models.TextField()),
                ('sneaker_type', models.TextField()),
                ('description', models.TextField()),
                ('debut_year', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sneaker_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('debut_year', models.CharField(max_length=100)),
            ],
        ),
    ]
