# Generated by Django 4.2.7 on 2023-12-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='icon_title',
            new_name='sneaker',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='name',
            new_name='why',
        ),
        migrations.RenameField(
            model_name='user_sneaker',
            old_name='name',
            new_name='sneaker',
        ),
        migrations.AddField(
            model_name='user_sneaker',
            name='price',
            field=models.CharField(default='price = models.CharField(max_length=100, null=True)', max_length=100),
            preserve_default=False,
        ),
    ]
